# Generated by Django 6.0.4 on 2026-04-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alienid",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Alien ID",
                "verbose_name_plural": "Alien IDs",
            },
        ),
        migrations.RemoveField(
            model_name="alienid",
            name="full_name",
        ),
        migrations.AddField(
            model_name="alienid",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alienid",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="alienid",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="alienid",
            name="rin",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="alienid",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="alienid",
            name="hashed_rin",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="alienid",
            name="id_number",
            field=models.CharField(
                db_index=True,
                help_text="The Alien ID card number (e.g., 123456)",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="alienid",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates if this ID is currently valid in the registry",
            ),
        ),
    ]
